"""
odoo-bootstrap osm-setup / osm-index / osm-start:
Tích hợp Viindoo odoo-semantic-server — AI hiểu Odoo ORM,
view inheritance, dependency graph — không hallucinate.
"""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import time
from pathlib import Path

from rich.console import Console
from rich.panel import Panel

from odoo_bootstrap.core.constants import WORKSPACE_ROOT
from odoo_bootstrap.core.logger import get_logger

logger = get_logger("osm")
console = Console()

OSM_DIR = WORKSPACE_ROOT / "shared" / "odoo-semantic-server"
OSM_REPO = "https://github.com/Viindoo/odoo-semantic-server.git"
OSM_COMPOSE = OSM_DIR / "docker-compose.yml"
OSM_ENV = OSM_DIR / ".env"
OSM_PORT_MCP = 8765
OSM_PORT_NEO4J = 7474


def _run(
    cmd: list[str], cwd: Path | None = None, check: bool = True
) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, check=check, capture_output=False)


def _run_silent(cmd: list[str], cwd: Path | None = None) -> tuple[int, str]:
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return r.returncode, r.stdout + r.stderr


def _service_running(name: str) -> bool:
    code, _ = _run_silent(["docker", "ps", "--filter", f"name={name}", "--format", "{{.Names}}"])
    return name in _


def run_osm_setup() -> None:
    """Clone OSM, cấu hình .env, start Neo4j + pgvector."""

    console.print(
        Panel(
            "[bold cyan]Viindoo odoo-semantic-server Setup[/bold cyan]\n"
            "AI hiểu ORM, view inheritance, dependency graph\n"
            "Không hallucinate field/method names",
            title="OSM Setup",
        )
    )

    # ── Bước 1: Clone repo ────────────────────────────────────────────
    if (OSM_DIR / ".git").exists():
        console.print("[green]✓ OSM repo đã có, đang pull...[/green]")
        _run(["git", "pull", "--ff-only"], cwd=OSM_DIR)
    else:
        console.print(f"[cyan]→ Clone {OSM_REPO}...[/cyan]")
        OSM_DIR.parent.mkdir(parents=True, exist_ok=True)
        _run(["git", "clone", "--depth", "1", OSM_REPO, str(OSM_DIR)])
        console.print("[green]✓ Clone xong[/green]")

    # ── Bước 2: Tạo .env ─────────────────────────────────────────────
    if not OSM_ENV.exists():
        console.print("[cyan]→ Tạo .env...[/cyan]")
        neo4j_password = secrets.token_urlsafe(16)
        pg_password = secrets.token_urlsafe(16)
        pg_dsn = f"postgresql://odoo_semantic:{pg_password}@localhost:5433/odoo_semantic"

        env_content = f"""# Generated by odoo-bootstrap
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD="{neo4j_password}"
PG_DSN="{pg_dsn}"
PG_PASSWORD="{pg_password}"
NEO4J_IMAGE=neo4j:5.26.25
PG_IMAGE=pgvector/pgvector:0.8.2-pg16
NEO4J_TEST_URI=bolt://localhost:7687
NEO4J_TEST_USER=neo4j
NEO4J_TEST_PASSWORD="{neo4j_password}"
EMBEDDER_BASE_URL=http://localhost:11434
"""
        OSM_ENV.write_text(env_content)
        console.print("[green]✓ .env đã tạo[/green]")

        # Lưu password để dùng lại
        creds_file = OSM_DIR / ".osm-creds"
        creds_file.write_text(
            f"NEO4J_PASSWORD={neo4j_password}\n" f"PG_PASSWORD={pg_password}\n" f"PG_DSN={pg_dsn}\n"
        )
    else:
        console.print("[green]✓ .env đã tồn tại[/green]")

    # ── Bước 3: Start DB tier (Neo4j + pgvector) ──────────────────────
    console.print("[cyan]→ Start Neo4j + pgvector...[/cyan]")
    _run(["docker", "compose", "-f", str(OSM_COMPOSE), "up", "-d"], cwd=OSM_DIR)

    # Wait for Neo4j
    console.print("[dim]Chờ Neo4j sẵn sàng (tối đa 60s)...[/dim]")
    for i in range(12):
        time.sleep(5)
        code, out = _run_silent(
            [
                "docker",
                "exec",
                "odoo-semantic-mcp-neo4j-1",
                "cypher-shell",
                "-u",
                "neo4j",
                "-p",
                "password",
                "RETURN 1",
            ]
        )
        if code == 0:
            console.print("[green]✓ Neo4j sẵn sàng[/green]")
            break
        console.print(f"[dim]  Đang chờ... ({(i+1)*5}s)[/dim]")

    # ── Bước 4: Cài Python deps (uv) ─────────────────────────────────
    uv_bin = shutil.which("uv")
    if not uv_bin:
        console.print(
            "[red]uv chưa cài. Chạy: curl -LsSf https://astral.sh/uv/install.sh | sh[/red]"
        )
        return

    console.print("[cyan]→ Cài Python dependencies (uv sync)...[/cyan]")
    _run([uv_bin, "sync"], cwd=OSM_DIR)
    console.print("[green]✓ Dependencies đã cài[/green]")

    # ── Bước 5: Chạy database migration ──────────────────────────────
    console.print("[cyan]→ Init database schema...[/cyan]")
    venv_python = OSM_DIR / ".venv" / "bin" / "python"
    if not venv_python.exists():
        venv_python = Path(os.path.expanduser("~/.venv/odoo-semantic-mcp/bin/python"))

    if venv_python.exists():
        _run([str(venv_python), "-m", "src.migrate"], cwd=OSM_DIR, check=False)
        console.print("[green]✓ Schema khởi tạo xong[/green]")

    # ── Tổng kết ──────────────────────────────────────────────────────
    console.print()
    console.print(
        Panel(
            "[bold green]✓ OSM Setup hoàn tất![/bold green]\n\n"
            f"Neo4j UI:  [cyan]http://localhost:{OSM_PORT_NEO4J}[/cyan]\n"
            f"MCP Port:  [cyan]{OSM_PORT_MCP}[/cyan]\n\n"
            "Bước tiếp theo:\n"
            "  [cyan]odoo-bootstrap osm-index kh19ce[/cyan]  ← index custom addons\n"
            "  [cyan]odoo-bootstrap osm-start[/cyan]          ← start MCP server",
            title="Hoàn tất",
        )
    )


def run_osm_index(project_name: str, config_manager) -> None:
    """Index custom_addons của project vào OSM."""
    proj = config_manager.get_project(project_name)
    if not proj:
        console.print(f"[red]Project '{project_name}' không tồn tại[/red]")
        return

    if not OSM_DIR.exists():
        console.print("[red]OSM chưa cài. Chạy: odoo-bootstrap osm-setup[/red]")
        return

    addons_dir = proj.custom_addons_dir
    console.print(f"\n[bold]OSM Index:[/bold] {project_name} → {addons_dir}")

    # Tim venv python
    venv_python = OSM_DIR / ".venv" / "bin" / "python"
    if not venv_python.exists():
        venv_python = Path(os.path.expanduser("~/.venv/odoo-semantic-mcp/bin/python"))

    if not venv_python.exists():
        console.print("[red]OSM venv không tìm thấy. Chạy: odoo-bootstrap osm-setup[/red]")
        return

    # Lay Odoo source dir
    source_dir = WORKSPACE_ROOT / "versions" / str(proj.version) / "source"
    enterprise_dir = WORKSPACE_ROOT / "versions" / str(proj.version) / "enterprise"

    cmd = [
        str(venv_python),
        "-m",
        "src.indexer.cli",
        "--version",
        str(proj.version),
        "--addons",
        str(addons_dir),
    ]

    if source_dir.exists():
        cmd += ["--odoo-source", str(source_dir)]
    if enterprise_dir.exists() and any(enterprise_dir.iterdir()):
        cmd += ["--enterprise", str(enterprise_dir)]

    console.print(f"[cyan]→ Indexing Odoo {proj.version} addons...[/cyan]")
    console.print("[dim]Lần đầu có thể mất 5-15 phút[/dim]")

    env = {**os.environ}
    if OSM_ENV.exists():
        for line in OSM_ENV.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip().strip('"')

    result = subprocess.run(cmd, cwd=OSM_DIR, env=env, check=False)
    if result.returncode == 0:
        console.print(f"[green]✓ Index xong — {addons_dir.name}[/green]")
    else:
        console.print(f"[yellow]⚠ Indexer exit {result.returncode} — kiểm tra log[/yellow]")


def run_osm_start() -> None:
    """Start OSM MCP server."""
    if not OSM_DIR.exists():
        console.print("[red]OSM chưa cài. Chạy: odoo-bootstrap osm-setup[/red]")
        return

    venv_python = OSM_DIR / ".venv" / "bin" / "python"
    if not venv_python.exists():
        venv_python = Path(os.path.expanduser("~/.venv/odoo-semantic-mcp/bin/python"))

    env = {**os.environ}
    if OSM_ENV.exists():
        for line in OSM_ENV.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip().strip('"')

    console.print(f"[cyan]→ Start OSM MCP server tại port {OSM_PORT_MCP}...[/cyan]")
    console.print("[dim]Ctrl+C để dừng[/dim]\n")

    try:
        subprocess.run(
            [str(venv_python), "-m", "src.mcp.server"],
            cwd=OSM_DIR,
            env=env,
        )
    except KeyboardInterrupt:
        console.print("\n[dim]OSM server đã dừng[/dim]")


def run_osm_status() -> None:
    """Kiểm tra trạng thái OSM."""
    items = [
        ("OSM repo", OSM_DIR.exists()),
        ("Neo4j", _service_running("neo4j")),
        ("pgvector", _service_running("postgres")),
        ("uv", bool(shutil.which("uv"))),
    ]
    console.print("\n[bold]OSM Status:[/bold]")
    for name, ok in items:
        icon = "[green]✓[/green]" if ok else "[red]✗[/red]"
        console.print(f"  {icon} {name}")

    if OSM_DIR.exists():
        console.print(f"\n  Neo4j UI: [cyan]http://localhost:{OSM_PORT_NEO4J}[/cyan]")
        console.print(f"  MCP Port: [cyan]{OSM_PORT_MCP}[/cyan]")
